services: 
    upload:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/home/adl/my-adl-project
            - /etc/localtime:/etc/localtime:ro
        container_name: my-adl-project
        stdin_open: true # docker run -i
        tty: true        # docker run -t
